version: '3'

services:  
   db:
     image: hypriot/rpi-mysql
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
  
   wordpress:
     image: wordpress:latest
     ports:
       - 80
     deploy:
      labels:
        - traefik.port=80
        - traefik.frontend.rule=Host:${YOUR_FQDN_DOMAIN}
        - traefik.docker.network=proxy_agent_network
     networks:
      - default
      - proxy_agent_network
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     
volumes:
    db_data:

networks:
  proxy_agent_network:
    external: true
