version: '3'

services:  
   db:
     image: hypriot/rpi-mysql
     networks:
      - vdcsproxy_traefik-net
     volumes:
        - db_data:/var/lib/mysql    
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  
   wordpress:
     image: wordpress:latest
     ports:
       - 80
     deploy:
      labels:
        - traefik.enable=true
        - traefik.port=80
        - traefik.frontend.rule=Host:${YOUR_FQDN_DOMAIN}
        - traefik.docker.network=vdcsproxy_traefik-net
     networks:
      - vdcsproxy_traefik-net
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}

volumes: 
  db_data:
  
networks:
  vdcsproxy_traefik-net:
    external: true
