version: '3'

services:
   db:
     image: hypriot/rpi-mysql
     networks:
      - proxy_agent_network
     volumes:
       - db_data:/var/lib/mysql
     deploy:
      replicas: 1
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}

   wordpress:
     image: wordpress:latest
     networks:
      - proxy_agent_network
      depends_on:
      - db
     deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.backend=:${YOUR_FQDN_DOMAIN}
        - traefik.port=80
        - traefik.docker.network=proxy_agent_network
        - traefik.frontend.rule=Host:${YOUR_FQDN_DOMAIN}
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_USER_PASSWORD}

volumes:
    db_data:

networks:
  proxy_agent_network:
