version: '3'

services:  
   db:
     image: hypriot/rpi-mysql
     networks:
      - web_proxy
     volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - db_data:${WEB_VOL}/db_data/var/lib/mysql    
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  
   wordpress:
     image: wordpress:latest
     volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - wp_data:${WEB_VOL}/wp_data  
     deploy:
      labels:
        - traefik.enable=true
        - traefik.port=${HOST_PORT}
        - traefik.frontend.rule=Host:${YOUR_FQDN_DOMAIN}
        - traefik.docker.network=vdcsproxy_traefik-net
     networks:
      - web_proxy
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}

volumes: 
  db_data:
  wp_data:
  
networks:
  web_proxy:
    external: true
